### ISSUE TITLE
fix: MacOs 15.3.2 + XCode 16.3 = Unable to build iOS nor MacOS

### ISSUE THREAD

**Issue by JamesFieldist** [alnitak/flutter_recorder#32]
**Description**
clang: error: unsupported option '-msse' for target 'arm64-apple-macos15.0'
clang: error: unsupported option '-msse2' for target 'arm64-apple-macos15.0'
clang: error: unsupported option '-msse3' for target 'arm64-apple-macos15.0'
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')

**Steps To Reproduce**

1. flutter create
2. flutter pub add flutter_recorder
3. flutter build macos (or flutter build ios)

**Expected Behavior**

Should work as normal

**Additional Context**

Worked fine in Xcode 16.2, only failed when xcode automatically updated.

**Comment by bphillips09** [comment]
Just ran into this issue as well and traced it back to Xcode 16.3 as well

**Comment by JamesFieldist** [comment]
Right now even trying to downgrade to 16.2 results in thes ame issues. Hoping this gets released soon.

**Comment by alnitak** [comment]
I have published a new `macosIntrinsics` with the fix. Upgrading XCode to 16.3 also raised errors on my x86_64 machine, but I cannot try it on an arm64.

@JamesFieldist, @bphillips09 can you please try on your machine and verify that it is working for you? Just replace in your `pubspec.yaml` this line:
```
flutter_recorder: ^1.1.0
```
with this:
```
flutter_recorder:
  git:
    url: https://github.com/alnitak/flutter_recorder.git
    ref: macosIntrinsics
```

Thanks!

**Comment by JamesFieldist** [comment]
Still fails. Even the example app fails.

{ platform:macOS, arch:arm64, id:00006041-0000703E1468801C, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006041-0000703E1468801C, name:My Mac }
error: unknown target CPU 'apple-m1'
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by JamesFieldist** [comment]
https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes

This has some clues that might have a temporary fix:

Clang now defines TARGET_OS_* conditionals as built-in macros based on the provided target triple. This extension can be disabled with the flag -fno-define-target-os-macros. (111414452)

libc++ no longer supports std::allocator<const T> and containers of const-qualified element type, such as std::vector<const T> and std::list<const T>. This used to be supported as an undocumented extension. If you were using std::vector<const T>, replace it with std::vector<T> instead. The _LIBCPP_ENABLE_REMOVED_ALLOCATOR_CONST macro can be defined to temporarily re-enable this extension. This compatibility macro will be removed in a future release. To assist with the clean-up process, consider running your code through Clang Tidy, with [std-allocator-const](https://clang.llvm.org/extra/clang-tidy/checks/portability/std-allocator-const.html) enabled.

**Comment by alnitak** [comment]
> Clang now defines TARGET_OS_* conditionals as built-in macros based on the provided target triple. This extension can be disabled with the flag -fno-define-target-os-macros. (111414452)

This looks promising! Do you have a chance to try?

**Comment by JamesFieldist** [comment]
I don't know what to do to make this work, just saw clang stuff in the release notes and copied it out.  Adding -fnoxxx to the options in the pod stuff didn't change results.

**Comment by JamesFieldist** [comment]
PS: This only appears now if you try and do a release build for macos. It appears fine for iOS now.

**Comment by alnitak** [comment]
It seems that the same issue affecting flutter_soloud has been resolved with this flutter_recorder fix.

I am releasing an update, but feel free to reopen this issue if some problems still occur!
